version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: movies_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviedb
    ports:
      - "5439:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
